- name: Teardown Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  roles:
    - teardown_database

- name: Teardown app_servers flask configuration
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
  roles:
    - teardown_app

- name: Teardown haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  tags:
    - load_balancers
  roles:
    - teardown_loadbalancer
