---
# tasks file for roles/add_subscription
- name: Gather network facts
  setup:
    gather_subset:
      - 'network'
  delegate_facts: true
  delegate_to: control
#  connection: local

- debug:
    msg: "{{ hostvars['control'].ansible_default_ipv4.address }}, {{ hostvars['control'].ansible_dns.nameservers.0 }}, {{ hostvars['control'].ansible_dns.nameservers.1 }}"
    
- name: Insert DNS IP
  command: >-
    nmcli connection modify "System eth0"
    ipv4.ignore-auto-dns yes
    ipv4.dns {{ hostvars['control'].ansible_default_ipv4.address }}
    +ipv4.dns {{ hostvars['control'].ansible_dns.nameservers.1 }}
    +ipv4.dns 8.8.8.8
  register: network_update

- name: restart network manager
  service:
    name: NetworkManager
    state: restarted
  when: network_update.changed | bool

- name: install katello-ca-consumer package
  yum:
    name: "{{ satellite_katellocert }}"
    state: present
    disable_gpg_check: true

- name: register system and attach subs
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true
